-- Active: 1671708805339@@127.0.0.1@3308@airlinesdb_new

DROP TABLE AIRPORT;

DROP TABLE Airline_company;

DROP TABLE AIRPLANE;

DROP TABLE PLANE_PORT_ACCESS;

DROP TABLE SEAT;

DROP TABLE END_USER;

DROP TABLE FLIGHT_TRIP;

DROP TABLE FARE;

DROP TABLE TRAVELLER;

DROP TABLE TRAVELLER_TICKET;

DROP TABLE Airplane_Routes_Schedule;

DROP TABLE Airplane_Flight_Trips;
